import Head from 'next/head'
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import { Inter } from '@next/font/google'
import Header from '@/container/hoc/Header';

const inter = Inter({ subsets: ['latin'] })

function Home() {
  return (
    <>
      <Head>
        <meta name='description" content="Generated by CRUD Operation' />
        <meta name='viewport" content="width=device-width, initial-scale=1' />
        <title>Welcome to CRUD Operation</title>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container'>
        <Header/>
      </main>
    </>
  )
}
export default Home;
